config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  get 'timeline', to: 'home#timeline'
  get 'ranking', to: 'home#ranking'
  get 'search', to: 'search#search'
  get 'reviews/search', to: 'reviews#search'
  get 'users/search', to: 'users#search'
  # get 'users/:user_id/interest', to: 'users#interest', as: 'user_interest'
  # get 'users/:user_id/reviews', to: 'users#reviews', as: 'user_reviews'
  get 'users/edit', to: 'users#edit'
  get 'home/about'
  post '/home/guest_sign_in', to: 'home#new_guest'

  devise_for :users # , controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy] # /users/:user_id/relationships :relationships_idは不要なのでresource
    # get :followings, on: :member # /users/:id/followings 自分がフォローしている人一覧の画面用のルーティング。memberをつけることで/:idが入る。collectionだと/:idは入らない
    # get :followers, on: :member # /users/:id/followers 自分をフォローしている人一覧の画面用のルーティング。memberをつけることで/:idが入る。collectionだと/:idは入らない
  end
  resources :movies, only: %i[index show] do
    resource :interest, only: %i[create destroy] # /movies/:movie_id/interest ①movie_idをURLに持たせることでinterestのsave時などでmovie_idを取得しやすいのでネストにしている。②/:interest_idは不要(showページ不要)なのでresource。
  end
  resources :reviews do
    resource :good, only: %i[create destroy] # /reviews/:review_id/good ①review_idをURLに持たせることでgoodのsave時などでreview_idを取得しやすいのでネストにしている。②/:good_idは不要(showページ不要)なのでresource。
    resource :bad, only: %i[create destroy] # /reviews/:review_id/bad ①review_idをURLに持たせることでbadのsave時などでreview_idを取得しやすいのでネストにしている。②/:bad_idは不要(showページ不要)なのでresource。
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  validates :name, uniqueness: :true, length: { maximum: 10 },
                  format: { with: /\A[a-zA-Z0-9]+\z/, message: "を半角英数字で入力してください"}
  enum sex: { '--': 0, 男: 1, 女: 2, その他: 9 }
  has_many :goods
  has_many :bads

  has_many :reviews, dependent: :destroy
  has_many :good_reviews, through: :goods, source: :review # has_many a, through: :b で、bを通したuser.aが使える。aをreviewsにするとhas_many :reviewsと被ってしまう為、sourceにモデル名を書いた上でaの名前を変えている
  has_many :bad_reviews, through: :bads, source: :review # has_many a, through: :b で、bを通したuser.aが使える。aをreviewsにするとhas_many :reviewsと被ってしまう為、sourceにモデル名を書いた上でaの名前を変えている

  has_many :interests, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id # 外部キーをfollowing_idとしているので、フォローする側から見たRelasionships
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id # 外部キーをfollower_idとしているので、フォローされる側から見たRelasionships
  has_many :followers, through: :passive_relationships, source: :following

  attachment :image

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: %i[facebook google_oauth2 twitter]

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid: auth.uid, provider: auth.provider, email: User.dummy_email(auth), password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  # name検索機能
  # def self.search(search_word, search_type)
  #   case search_type
  #   when '1' # 完全一致
  #     User.where(['name LIKE ?', "#{search_word}"])
  #   when '2' # 前方一致
  #     User.where(['name LIKE ?', "#{search_word}%"])
  #   when '3' # 後方一致
  #     User.where(['name LIKE ?', "%#{search_word}"])
  #   else # 部分一致
  #     User.where(['name LIKE ?', "%#{search_word}%"])
  #   end
  # end

  def followed_by?(user)
    passive_relationships.where(following_id: user.id).present? #exists?の方がいいかも
  end

  def timeline
    Review.where("user_id IN (?)", following_ids)
  end

  def self.follower_ranks
    User.find(Relationship.group(:follower_id).order('count(follower_id) desc').limit(3).pluck(:follower_id))
  end

  def avatar_url # プロフィール画像を表示する。なければno_profile_imageを表示
    return "no_profile_image.jpg" if image_id.nil?
    generate_avatar_url
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

  def generate_avatar_url
    "https://lambda-s3-practice-resize.s3-ap-northeast-1.amazonaws.com/store/" + image_id.to_s + "-thumbnail."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Common
  before_action :authenticate_user!, except: [:index]
  before_action :ensure_correct_user, only: [:edit]
  before_action :set_tmdb_key, only: [:show]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.page(params[:page]).reverse_order
    @good_reviews = @user.good_reviews.page(params[:page]).reverse_order
    @bad_reviews = @user.bad_reviews.page(params[:page]).reverse_order
    @user_interests = Interest.where(user_id: current_user.id)

    @user_followings = @user.followings.page(params[:page])
    @user_followers = @user.followers.page(params[:page])

    gon.movie_id = Review.all.pluck(:movie_id)
    gon.review_id = Review.all.pluck(:id)

    @interests = @user.interests.page(params[:page])
    @current_user_reviews = current_user.reviews
    @score_reviews = Review.select(:movie_id, :total_score)
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      sleep(3)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

  def search
    @q = User.search(search_params)
    @users = @q.result(distinct: true).page(params[:page]).reverse_order
    render :index
  end

  private

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      flash[:notice] = "このページにはアクセスできません"
      redirect_back(fallback_location: user_path(current_user))
    elsif @user.id == 2
      redirect_to request.referer, notice: "ゲストユーザーは編集機能を使用できません"
    else
      render :edit
    end
  end

  def user_params
      params.require(:user).permit(:name, :image, :email, :birthday, :sex, :intro)
  end

  def search_params
    params.require(:q).permit(:name_cont, :intro_cont, :sex_eq, :birthday_gteq, :birthday_lteq, :birthday_to_age_gteq, :birthday_to_age_lteq)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def age(birthday)
    (Date.today.strftime('%Y%m%d').to_i - birthday.strftime('%Y%m%d').to_i) / 10000
  end
end

app/views/users/_interests.html.slim
= paginate interests
.flex#interests_flex
  - interests.each do |interest|
    .item.card.img-thumbnail.shadow-sm.m-1#interests_item
      = link_to movie_path(interest.movie_id)
        = image_tag  "https://image.tmdb.org/t/p/w200#{interest.poster_path}", class:"w-100"
      .card-body
        strong = interest.title
        div.card-text#interest_total_score_avg
          - if score_reviews.where(movie_id: interest.movie_id).present?
            - movie_score_reviews = score_reviews.where(movie_id: interest.movie_id)
            - movie_total_score_sum = movie_score_reviews.inject(0) {|sum, hash| sum + hash[:total_score]}
            - movie_total_score_avg = movie_total_score_sum.fdiv(movie_score_reviews.length)
            p id="score_avg_movie-#{interest.movie_id}"  ="平均スコア #{movie_total_score_avg.ceil(1)}"
            javascript:
              $('#score_avg_movie-#{interest.movie_id}').raty({ size: 36, starOff: "#{asset_path 'star-off.png'}", starOn : "#{asset_path 'star-on.png'}", starHalf: "#{asset_path 'star-half.png'}",
                scoreName: 'review[total_score]', half: true, score: #{movie_total_score_avg}, readOnly: true
              });
          - else
            p レビュー無し
        p.mb-0
          ////レビュー済み/する
          - if current_user_reviews.find_by(movie_id: interest.movie_id).present?
            = link_to "レビュー済み", review_path(current_user_reviews.find_by(movie_id: interest.movie_id)), class:"btn btn-info btn-sm mr-2"
          - else
            = link_to "レビューする", new_review_path(movie_id: interest.movie_id, title: interest.title, poster_path: interest.poster_path), class:"btn btn-warning btn-sm mr-2"
          ////観たいリストに追加、削除する
          - if current_user.interests.find_by(movie_id: interest.movie_id).present?
            = link_to "追加済み", movie_interest_path(interest.movie_id), class:"btn btn-info btn-sm mr-2", method: :delete, data: { confirm: '観たいリストから削除してもよろしいですか？' }
          - else
            = link_to "観たい", movie_interest_path(movie_id: interest.movie_id, title: interest.title, poster_path: interest.poster_path), class:"btn btn-warning btn-sm mr-2", method: :post

= paginate interests

app/views/users/_user_show.html.slim
  div.card.container.shadow-sm id="user_show_container"
    div.user_head.row.mt-4.mb-4
      .col-md-3.text-center= image_tag  user.avatar_url, size: "50x50", class: "img-circle pull-left profile-thumb rounded-circle"
      .col-md-9.d-flex.align-items-center.h3=  user.name
    div.py-4.row
      .col-md-3.text-center
        - if user.birthday.present?
          | 年齢: #{age(user.birthday)}歳
        br
        - if user.sex.present?
          | 性別: #{user.sex}
      p.col-md-9= user.intro
    - if user != current_user
      - if user.followed_by?(current_user)
        = link_to 'フォロー済み', user_relationships_path(user), class:"btn btn-info btn-sm mb-4 col-md-3 mx-auto", method: :delete
      - else
        = link_to 'フォローする', user_relationships_path(user), class:"btn btn-warning btn-sm mb-4 col-md-3 mx-auto", method: :post
    - if user == current_user
      = link_to '編集 / 退会', edit_user_path(user), class:"btn btn-primary btn-sm mb-4 col-md-3 mx-auto"

app/views/users/_users.html.slim
  - users.each do |user|
    div.card.container.shadow-sm.movie_show_info
      div.user_head.mt-4.mb-4
        = link_to user_path(user), class:"row"
          .col-md-3= image_tag  user.avatar_url, size: "50x50", class: "img-circle pull-left profile-thumb rounded-circle"
          .col-md-9.d-flex.align-items-center.h3=  user.name
      .row
        .col-md.p-0
          div.text-center
            strong フォロワー
          div.text-center
            strong= "#{user.followers.count}"
        .col-md.p-0
          div.text-center
            strong フォロー
          div.text-center
            strong= "#{user.followings.count}"
      p.py-4.small
        - if user.birthday.present?
          | 年齢: #{age(user.birthday)}歳
        - if user.sex.present?
          | 　　性別: #{user.sex}
        br
        | #{user.intro}
      -if user_signed_in?
        - if user != current_user
          - if user.followed_by?(current_user)
            = link_to 'フォロー済み', user_relationships_path(user), class:"btn btn-info btn-sm mb-4", method: :delete, data: {confirm: 'フォローを外してもよろしいですか？'}
          - else
            = link_to 'フォローする', user_relationships_path(user), class:"btn btn-warning btn-sm mb-4", method: :post

app/views/users/_users_search.html.slim
div
  h5.search_heading.w-100 検索条件
  - if params[:q]
    div.search_field.px-1
      - unless params[:q][:birthday_to_age_gteq].empty?
        div.font-weight-bold 年齢: #{params[:q][:birthday_to_age_gteq]} 歳以上
      - unless params[:q][:birthday_to_age_lteq].empty?
        div.font-weight-bold 年齢: #{params[:q][:birthday_to_age_lteq]} 歳以下
      - unless params[:q][:sex_eq].empty?
        - if params[:q][:sex_eq] == '1'
          div.font-weight-bold 性別: 男
        - elsif params[:q][:sex_eq] == '2'
          div.font-weight-bold 性別: 女
        - else
          div.font-weight-bold 性別: その他
      - unless params[:q][:intro_cont].empty?
        div.font-weight-bold 自己紹介: #{params[:q][:intro_cont]}
      - unless params[:q][:name_cont].empty?
        div.font-weight-bold 名前: #{params[:q][:name_cont]}
  - else
    div.search_field.text-center 検索条件はありません

div
  h5.search_heading.w-100 ユーザー検索
  div.search_field.px-1
    = search_form_for(q, url:users_search_path) do |f|
      p.border-bottom
        = f.label :birthday, '年齢', class:"mr-2 font-weight-bold"
        br
        = f.number_field :birthday_to_age_gteq, in: 0..150, include_blank: true
        |  歳〜
        = f.number_field :birthday_to_age_lteq, in: 0..150, include_blank: true
        |  歳
      p.border-bottom
        = f.label :sex_eq, '性別', class:"mr-2 font-weight-bold"
        br
        = f.radio_button 'sex_eq', '', {:checked => true}
        = f.label :sex_eq_, '指定なし　'
        = f.radio_button 'sex_eq', '1'
        = f.label :sex_eq_1, '男　'
        = f.radio_button 'sex_eq', '2'
        = f.label :sex_eq_2, '女　'
        = f.radio_button 'sex_eq', '9'
        = f.label :sex_eq_9, 'その他'
      p
        = f.label :intro_cont, '自己紹介', class:"mr-2 font-weight-bold"
        = f.search_field :intro_cont
      p
        = f.label :name_cont, '名前', class:"mr-2 font-weight-bold"
        = f.search_field :name_cont
      div.text-center.mb-4
        = f.submit class:"btn btn-info rounded-pill"

app/views/users/edit.html.slim
= render 'layouts/errors', model: @user
.devise_container.text-center
  h2.mt-4 登録情報編集 / 退会
  = form_with model: @user, local: true do |f|
    .field.form-group
      = f.label :name, "Name(半角英数字, 10文字まで)"
      br
      = f.text_field :name

    .field.form-group
      = f.label :email, "Email"
      br
      = f.email_field :email

    .field.form-group
      = f.label :birthday, "生まれ年(任意)"
      br
      = f.date_select :birthday, {discard_month: true, discard_day: true, start_year: 1940, end_year: Time.now.year - 10, prompt:"--" }

    .field.form-group
      = f.label :sex, "性別(任意)"
      br
      = f.select :sex, User.sexes.keys, :selected=>@user.sex

    .field.form-group
      = f.label :intro, "自己紹介(任意)"
      br
      = f.text_area :intro, style:"width: 40%; height: 100px;"

    .form-group.has-icon
        div プロフィール画像(任意)
        .user-edit-image
          = image_tag  @user.avatar_url, size: "150x150", src: "", class: "img-circle pull-left profile-thumb rounded-circle", id: "img_prev"
        label.control-label.sr-only for="user_image"  ProfileImage
        = f.attachment_field :image, placeholder: "プロフィール画像", class: "user-edit-form", onchange: "previewFile()"

    .actions.mx-auto.row.mt-5
      div.col-md
      div.col-md= f.submit "更新する", class:"btn btn-success"
      div.col-md= link_to '退会する', user_registration_path(@review), class:"btn btn-danger", method: :delete, data: {confirm: 'アカウントを削除してもよろしいですか？'}
      div.col-md
javascript:
  function previewFile() {
    var preview = document.querySelector('#img_prev');
    //どこでプレビューするか指定。'img[name="preview"]'などにすればimg複数あっても指定できます。
    var file    = document.querySelector('input[type=file]').files[0];
    var reader  = new FileReader();

    if (file) {
      reader.readAsDataURL(file);
    };

    reader.addEventListener("load", function () {
      preview.src = reader.result;
    }, false);
  }

app/views/users/index.html.slim
.heading ユーザーを探す
= paginate @users

div.row
  div.card.col-md-3.px-0.shadow-sm style="height: fit-content;"
    = render 'users/users_search', q: @q
  div.flex.col-md-9
    = render 'users/users', users: @users
= paginate @users

app/views/users/show.html.slim
.heading= "#{@user.name}さんのページ"

= render 'users/user_show', user: @user

.wrap
  ul#tab-menu.clearfix
    li
      a.active href="#tab_followers"
        div
          strong.tab-menu_label フォロワー
        div
          strong= @user.followers.count
    li
      a href="#tab_followings"
        div
          strong.tab-menu_label フォロー
        div
          strong= @user.followings.count
    li
      a href="#tab_goods"
        div
          strong.tab-menu_label GOODしたレビュー
        div
          strong= @good_reviews.count
    li
      a href="#tab_bads"
        div
          strong.tab-menu_label BADしたレビュー
        div
          strong= @bad_reviews.count
    li
      a href="#tab_reviews"
        div
          strong.tab-menu_label= "#{@user.name}さんのレビュー"
        div
          strong= @reviews.count
    li
      a href="#tab_interests"
        div
          strong.tab-menu_label= "#{@user.name}さんの観たいリスト"
        div
          strong= "#{@user.interests.count}"
  #tab-contents.clearfix
    #tab_followers.tab
      = paginate @user_followers
      .flex.user_show_container
        = render 'users/users', users: @user_followers
      = paginate @user_followers
    #tab_followings.tab
      = paginate @user_followings
      .flex.user_show_container
        = render 'users/users', users: @user_followings
      = paginate @user_followings
    #tab_goods.tab
      = render 'reviews/good_bad_reviews', reviews: @good_reviews
    #tab_bads.tab
      = render 'reviews/good_bad_reviews', reviews: @bad_reviews
    #tab_reviews.tab
      = render 'reviews/reviews', reviews: @reviews
    #tab_interests.tab
      = render 'users/interests', {interests: @interests, movie_total_score_avg: @movie_total_score_avg, score_reviews: @score_reviews, current_user_reviews: @current_user_reviews}

javascript:
  $('#tab-contents .tab[id != "tab_followers"]').hide();

  $('#tab-menu a').on('click', function() {
    $("#tab-contents .tab").hide();
    $("#tab-menu .active").removeClass("active");
    $(this).addClass("active");
    $($(this).attr("href")).show();
    return false;
  });