config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  get 'timeline', to: 'home#timeline'
  get 'ranking', to: 'home#ranking'
  get 'search', to: 'search#search'
  get 'reviews/search', to: 'reviews#search'
  get 'users/search', to: 'users#search'
  # get 'users/:user_id/interest', to: 'users#interest', as: 'user_interest'
  # get 'users/:user_id/reviews', to: 'users#reviews', as: 'user_reviews'
  get 'users/edit', to: 'users#edit'
  get 'home/about'
  post '/home/guest_sign_in', to: 'home#new_guest'

  devise_for :users # , controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy] # /users/:user_id/relationships :relationships_idは不要なのでresource
    # get :followings, on: :member # /users/:id/followings 自分がフォローしている人一覧の画面用のルーティング。memberをつけることで/:idが入る。collectionだと/:idは入らない
    # get :followers, on: :member # /users/:id/followers 自分をフォローしている人一覧の画面用のルーティング。memberをつけることで/:idが入る。collectionだと/:idは入らない
  end
  resources :movies, only: %i[index show] do
    resource :interest, only: %i[create destroy] # /movies/:movie_id/interest ①movie_idをURLに持たせることでinterestのsave時などでmovie_idを取得しやすいのでネストにしている。②/:interest_idは不要(showページ不要)なのでresource。
  end
  resources :reviews do
    resource :good, only: %i[create destroy] # /reviews/:review_id/good ①review_idをURLに持たせることでgoodのsave時などでreview_idを取得しやすいのでネストにしている。②/:good_idは不要(showページ不要)なのでresource。
    resource :bad, only: %i[create destroy] # /reviews/:review_id/bad ①review_idをURLに持たせることでbadのsave時などでreview_idを取得しやすいのでネストにしている。②/:bad_idは不要(showページ不要)なのでresource。
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    good = current_user.goods.build(review_id: params[:review_id])
    good.save!
    bad = Bad.find_by(user_id: current_user.id, review_id: params[:review_id])
    if bad.present?
      bad.destroy
    end
    @msg = "GOODに追加しました"
  end

  def destroy
    @review = Review.find(params[:review_id])
    good = Good.find_by(user_id: current_user.id, review_id: params[:review_id])
    good.destroy!
    @msg = "GOODから削除しました"
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_good.html.slim
p このレビューに対する評価
//// GOODボタン
- if review.good_by?(current_user)
  = link_to review_good_path(review), class:"btn btn-warning btn-sm", method: :delete, remote: true do
    i.fas.fa-thumbs-up
    = review.goods.count
- else
  = link_to review_good_path(review), class:"btn btn-warning btn-sm", method: :post, remote: true do
    i.far.fa-thumbs-up
    = review.goods.count
//// BADボタン
- if review.bad_by?(current_user)
  = link_to review_bad_path(review), class:"btn btn-warning btn-sm", method: :delete, remote: true do
    i.fas.fa-thumbs-down
    = review.bads.count
- else
  = link_to review_bad_path(review), class:"btn btn-warning btn-sm", method: :post, remote: true do
    i.far.fa-thumbs-down
    = review.bads.count

app/views/goods/create.js.erb
$("#review-<%=@review.id%>_good").html("<%= j(render partial: 'goods/good', locals: { review: @review }) %>");
$('#alert-message').html('<div class="alert alert-success mt-1 auto-hide"><%= @msg %></div>');
$(function(){
    setTimeout("$('.auto-hide').fadeOut('slow')", 1500)
  });

$("#self_review-<%=@review.id%>_good").html("<%= j(render partial: 'goods/good', locals: { review: @review }) %>");

app/views/goods/destroy.js.erb
$("#review-<%=@review.id%>_good").html("<%= j(render partial: 'goods/good', locals: { review: @review }) %>");
$('#alert-message').html('<div class="alert alert-danger mt-1 auto-hide"><%= @msg %></div>');
$(function(){
    setTimeout("$('.auto-hide').fadeOut('slow')", 1500)
  });

$("#self_review-<%=@review.id%>_good").html("<%= j(render partial: 'goods/good', locals: { review: @review }) %>");