config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  get 'timeline', to: 'home#timeline'
  get 'ranking', to: 'home#ranking'
  get 'search', to: 'search#search'
  get 'reviews/search', to: 'reviews#search'
  get 'users/search', to: 'users#search'
  # get 'users/:user_id/interest', to: 'users#interest', as: 'user_interest'
  # get 'users/:user_id/reviews', to: 'users#reviews', as: 'user_reviews'
  get 'users/edit', to: 'users#edit'
  get 'home/about'
  post '/home/guest_sign_in', to: 'home#new_guest'

  devise_for :users # , controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[create destroy] # /users/:user_id/relationships :relationships_idは不要なのでresource
    # get :followings, on: :member # /users/:id/followings 自分がフォローしている人一覧の画面用のルーティング。memberをつけることで/:idが入る。collectionだと/:idは入らない
    # get :followers, on: :member # /users/:id/followers 自分をフォローしている人一覧の画面用のルーティング。memberをつけることで/:idが入る。collectionだと/:idは入らない
  end
  resources :movies, only: %i[index show] do
    resource :interest, only: %i[create destroy] # /movies/:movie_id/interest ①movie_idをURLに持たせることでinterestのsave時などでmovie_idを取得しやすいのでネストにしている。②/:interest_idは不要(showページ不要)なのでresource。
  end
  resources :reviews do
    resource :good, only: %i[create destroy] # /reviews/:review_id/good ①review_idをURLに持たせることでgoodのsave時などでreview_idを取得しやすいのでネストにしている。②/:good_idは不要(showページ不要)なのでresource。
    resource :bad, only: %i[create destroy] # /reviews/:review_id/bad ①review_idをURLに持たせることでbadのsave時などでreview_idを取得しやすいのでネストにしている。②/:bad_idは不要(showページ不要)なのでresource。
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.slim
- if model.errors.any?
  ul.alert.alert-danger.mt-1
    - model.errors.full_messages.each do |message|
      li= message

app/views/layouts/_footer.html.slim
footer
  .container
    nav
      .footer-note TMDb　Copyright © 2018 Julia Zhu. All rights reserved.
      ul
        li.footer-link = link_to "About", home_about_path

app/views/layouts/_header.html.slim
header.navbar
  nav.row
    .col-md-2
      div= link_to root_path, class:"logo"
        div style="font-size: 2rem;"
          i class="fas fa-film d-block"
        div Movie Review
    .nav_form.col-md-3
      = form_tag(search_path, :method => 'get') do
        = search_field_tag (:search_word)
        = hidden_field_tag :select, "1", checked: true
        = label_tag :registered_address, "映画のタイトルで", class:"mr-1"
        / レビュー一覧ページに検索機能つけたので廃止
        / = radio_button_tag :select, "2"
        / = label_tag :registered_address, "レビュー", class:"mr-1"
        / 一覧ページに検索機能つけたので廃止
        / = radio_button_tag :select, "3"
        / = label_tag :registered_address, "ユーザー", class:"mr-1"
        / = select_tag :search_type, options_for_select([['部分一致', '4'],['完全一致', '1'], ['前方一致', '2'], ['後方一致', '3'] ]), disabled: true, class:"mr-1"
        = submit_tag "検索", class:"btn btn-dark btn-sm rounded-pill"
    ul.nav_link.col-md-5
      li= link_to "人気の映画", movies_path
      li= link_to "レビューを探す", reviews_path
      li= link_to "ユーザーを探す", users_path
      li= link_to "ランキング", ranking_path
      - if user_signed_in?
        li= link_to  "タイムライン", timeline_path
    - if user_signed_in?
      div class="dropdown col-md-2"
        a class="btn btn-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" #{current_user.name}
        div class="dropdown-menu" aria-labelledby="dropdownMenuLink"
          = link_to  "マイページ", user_path(current_user), class:"dropdown-item"
          = link_to  "プロフィール編集", edit_user_path(current_user), class:"dropdown-item"
          = link_to  "ログアウト", destroy_user_session_path, method: :delete, class:"dropdown-item"
    - else
      .login
        = link_to "ログイン", user_session_path

javascript:

  // ラジオボタンのvalueによって、検索オプション(完全一致や前方一致など)の選択をできたりできなかったりする
  $(function() {
    $("input[value=1]").on('change', function() {
        $("select[name=search_type]").prop('disabled', true);
    });
    $("input[value=2]").on('change', function() {
        $("select[name=search_type]").prop('disabled', false);
    });
    $("input[value=3]").on('change', function() {
        $("select[name=search_type]").prop('disabled', false);
    });
  });

app/views/layouts/_timeline.html.slim
-if timeline_reviews.any?
  div.flex
  - timeline_reviews.each do |review|
    div.card.mb-2.shadow-sm id="good_bad_reviews_card"
      div.card-body
        div.row
          div.col-md-10
            div.card-title.row#review_index_card-title
                div.col-md-6= link_to review_path(review), id:"review_link", class:"row"
                  = image_tag  review.user.avatar_url, size: "40x40", class: "img-circle pull-left profile-thumb rounded-circle row"
                  p= "#{review.user.name}さんのレビュー #{review.created_at.strftime('%Y/%m/%d')}"
                strong.col-md-6 = review.title
            div
              h5 id="review_score-#{review.id}" 総合スコア #{review.total_score}
            = render 'reviews/tag_list', tag_list: review.tag_list
            div.review_index_body
              p.card-text #{review.body}

          div.col-md-2.review_index_poster
            = link_to movie_path(review.movie_id)
              = image_tag "https://image.tmdb.org/t/p/w200#{review.poster_path}"
        div
          div.review_index_card_footer.row
            div.row.review_index_good-bad id="self_review-#{review.id}_good"
              = render 'goods/good', review: review
            ////観たいリストに追加済み/する
            - if current_user.interests.find_by(movie_id: review.movie_id).present?
              p= link_to "観たいリストに追加済み", movie_interest_path(review.movie_id), class:"btn btn-info btn-sm", method: :delete
            - else
              p= link_to "この映画を観たい", movie_interest_path(movie_id: review.movie_id, title: review.title, poster_path: review.poster_path), class:"btn btn-warning btn-sm", method: :post
            ////フォロー済み/する
            - if review.user != current_user
              - if review.user.followed_by?(current_user)
                p= link_to 'このユーザーをフォロー済み', user_relationships_path(review.user), class:"btn btn-info btn-sm", method: :delete
              - else
                p= link_to 'このユーザーをフォローする', user_relationships_path(review.user), class:"btn btn-warning btn-sm", method: :post
            - if review.user == current_user
              = link_to "編集", edit_review_path(review), class:"btn btn-primary btn-sm mr-2"
              = link_to "削除", review_path(review), class:"btn btn-danger btn-sm", method: :delete, data: {confirm: 'このレビューを削除してもよろしいですか？'}

        javascript:
          $('#review_score-#{review.id}').raty({ size: 36, starOff: "#{asset_path 'star-off.png'}", starOn : "#{asset_path 'star-on.png'}", starHalf: "#{asset_path 'star-half.png'}",
            scoreName: 'review[total_score]', half: true, score: #{review.total_score}, readOnly: true
          });

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MovieReview
    = csrf_meta_tags
    = csp_meta_tag
    /gem 'gon' をjsファイルで使えるようにする
    = include_gon
    link href="https://fonts.googleapis.com/css?family=Francois+One&display=swap" rel="stylesheet"
    = favicon_link_tag('favicon.ico')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta[name='viewport' content='width=device-width, initial-scale=1']
  body
    = render 'layouts/header'
    - if request.path.include?("about")
      div.about_container.text-center
        #alert-message
        -if flash.notice.present?
          p.alert.alert-success.mt-1.auto-hide= flash.notice
        -if flash.alert.present?
          p.alert.alert-danger.mt-1.auto-hide= flash.alert
        = yield
    - else
      .container
        #alert-message
        -if flash.notice.present?
          p.alert.alert-success.mt-1.auto-hide= flash.notice
        -if flash.alert.present?
          p.alert.alert-danger.mt-1.auto-hide= flash.alert
        = yield
      div#back
        a href="#"
          img src="#{asset_path 'arrow.png'}" alt="最上部へ"
      = render 'layouts/footer'